import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// Configuração da Poppins
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins", // Opcional: define uma variável CSS
});

export const metadata: Metadata = {
  title: "Gustavo Ferreira / Portfolio",
  description: "Generated by create next app and Guis",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`} // Use a classe gerada automaticamente
      >
        {children}
      </body>
    </html>
  );
}